services:
  isp-config-service-1:
    image: "nexus.txix.ru/msp2/dev/isp-config-service:3.1.0"
    container_name: "isp-config-service-1"
    hostname: "isp-config-service-1"
    restart: unless-stopped
    environment:
      grpcOuterAddress.ip: isp-config-service-1
      rqlite.DataPath: "data"
      rqlite.NodeID: 1
      rqlite.BootstrapExpect: 3
      rqlite.RaftAddr: "isp-config-service-1:9008"
      rqlite.JoinAddrs: "isp-config-service-1:9008,isp-config-service-2:9008,isp-config-service-3:9008"
    volumes:
      - "./isp-config-service-1/data:/app/data"
  isp-config-service-2:
    image: "nexus.txix.ru/msp2/dev/isp-config-service:3.1.0"
    container_name: "isp-config-service-2"
    hostname: "isp-config-service-2"
    restart: unless-stopped
    environment:
      grpcOuterAddress.ip: isp-config-service-2
      rqlite.DataPath: "data"
      rqlite.NodeID: 2
      rqlite.BootstrapExpect: 3
      rqlite.RaftAddr: "isp-config-service-2:9008"
      rqlite.JoinAddrs: "isp-config-service-1:9008,isp-config-service-2:9008,isp-config-service-3:9008"
    volumes:
      - "./isp-config-service-2/data:/app/data"
  isp-config-service-3:
    image: "nexus.txix.ru/msp2/dev/isp-config-service:3.1.0"
    container_name: "isp-config-service-3"
    hostname: "isp-config-service-3"
    restart: unless-stopped
    environment:
      grpcOuterAddress.ip: isp-config-service-3
      rqlite.DataPath: "data"
      rqlite.NodeID: 3
      rqlite.BootstrapExpect: 3
      rqlite.RaftAddr: "isp-config-service-3:9008"
      rqlite.JoinAddrs: "isp-config-service-1:9008,isp-config-service-2:9008,isp-config-service-3:9008"
    volumes:
      - "./isp-config-service-3/data:/app/data"